name: ci-node-workflow
on: [push]
jobs:
  check_application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: yarn test